### ISSUE TITLE
Issue in database setup: ER_BAD_FIELD_ERROR: Unknown column 'deployments' in 'field list' 

### ISSUE THREAD

**Issue by ambrossRake** [om-mani-padme-hum/muddy#5]
After removing collation statements as a fix from the setup script I received this error while creating a new area in the web editor

Setup Script: [New Text Document (6).txt](https://github.com/om-mani-padme-hum/muddy/files/6798840/New.Text.Document.6.txt)

**Comment by om-mani-padme-hum** [comment]
Thanks, should be fixed now in v0.11.6
